name: kibunmeshi-dev

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kibunmeshi_development
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    volumes:
      - .:/app
      - bundle_data:/app/vendor/bundle
    entrypoint: []
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -lc "rm -f tmp/pids/server.pid && bin/rails db:prepare && bin/rails server -b 0.0.0.0"

volumes:
  db_data:
  bundle_data:
