services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graduation_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    volumes:
      - .:/app
      - bundle_data:/app/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -lc "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"

volumes:
  db_data:
  bundle_data:
