default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  port: 5432
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kibunmeshi_development

test:
  <<: *default
  database: kibunmeshi_test

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    url: <%= ENV['DATABASE_URL'] %>
    max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cache:
    <<: *primary_production
    database: kibunmeshi_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: kibunmeshi_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: kibunmeshi_production_cable
    migrations_paths: db/cable_migrate
