---
ベーコンエッグ:
- ブラックペッパー
パンケーキ:
- シナモン
焼き魚:
- 山椒
フレンチトースト:
- シナモン
オムレツ:
- ブラックペッパー
ホットサンド:
- マスタード
カレーライス:
- クミン
- コリアンダー
- ターメリック
- カルダモン
- 唐辛子
ラーメン:
- 唐辛子
- ガーリック
- 生姜
- ブラックペッパー
とんかつ:
- からし
ハンバーグ:
- ナツメグ
- ブラックペッパー
ステーキ:
- ローズマリー
- ブラックペッパー
唐揚げ:
- ガーリック
- 生姜
- ブラックペッパー
ピザ:
- オレガノ
- バジル
- ブラックペッパー
- 唐辛子
- ホワイトペッパー
ハンバーガー:
- ブラックペッパー
オムライス:
- ブラックペッパー
親子丼:
- 唐辛子
牛丼:
- 唐辛子
焼きそば:
- 唐辛子
- からし
お好み焼き:
- 唐辛子
- からし
たこ焼き:
- 唐辛子
- からし
かしみん焼き:
- 唐辛子
- からし
エビフライ:
- 唐辛子
- からし
チキンカツ:
- からし
カツカレー:
- クミン
- コリアンダー
- ターメリック
- カルダモン
- 唐辛子
ロコモコ:
- ブラックペッパー
タコライス:
- クミン
- コリアンダー
- パプリカ
- パセリ
ミートソースパスタ:
- オレガノ
- バジル
カルボナーラ:
- ブラックペッパー
- ホワイトペッパー
ペペロンチーノ:
- ガーリック
- 唐辛子
- パセリ
ナポリタン:
- オレガノ
- バジル
たらこパスタ:
- わさび
きのこパスタ:
- タイム
チャーハン:
- ガーリック
- ブラックペッパー
麻婆豆腐:
- 五香粉
- 山椒
- 唐辛子
エビチリ:
- 唐辛子
酢豚:
- ガーリック
回鍋肉:
- ガーリック
青椒肉絲:
- ガーリック
餃子:
- ガーリック
- からし
- ブラックペッパー
春巻き:
- ガーリック
- からし
- ブラックペッパー
エビマヨ:
- ガーリック
- ブラックペッパー
グラタン:
- ナツメグ
- ブラックペッパー
- ホワイトペッパー
シチュー:
- ナツメグ
- ブラックペッパー
- ホワイトペッパー
ドリア:
- ナツメグ
- ブラックペッパー
- ホワイトペッパー
ラザニア:
- ナツメグ
- ブラックペッパー
- ホワイトペッパー
ローストチキン:
- ローズマリー
- ブラックペッパー
ローストビーフ:
- ローズマリー
- ブラックペッパー
チキンソテー:
- ローズマリー
- ブラックペッパー
寿司:
- わさび
刺身:
- わさび
天ぷら:
- 唐辛子
すき焼き:
- 唐辛子
しゃぶしゃぶ:
- 唐辛子
焼き鳥:
- 唐辛子
- 山椒
うな重:
- 山椒
かつ丼:
- 唐辛子
天丼:
- 唐辛子
海鮮丼:
- わさび
鉄火丼:
- わさび
ちらし寿司:
- わさび
手巻き寿司:
- わさび
おでん:
- からし
肉じゃが:
- からし
豚の角煮:
- ガーリック
- 生姜
- からし
鶏の照り焼き:
- 生姜
- 唐辛子
生姜焼き:
- 生姜
- 唐辛子
チキン南蛮:
- 唐辛子
- ブラックペッパー
山形風芋煮:
- 唐辛子
宮城風芋煮:
- 唐辛子
芋の子汁:
- 唐辛子
グリーンカレー:
- クミン
- コリアンダー
- ターメリック
- カルダモン
- 唐辛子
ガパオライス:
- バジル
- 唐辛子
- コリアンダー
パッタイ:
- 唐辛子
- コリアンダー
- バジル
トムヤムクン:
- 唐辛子
- コリアンダー
- バジル
タンドリーチキン:
- クミン
- コリアンダー
- ターメリック
- カルダモン
- 唐辛子
バターチキンカレー:
- クミン
- コリアンダー
- ターメリック
- カルダモン
- 唐辛子
キーマカレー:
- クミン
- コリアンダー
- ターメリック
- カルダモン
- 唐辛子
ナン:
- クミン
タコス:
- クミン
- コリアンダー
- パプリカ
ブリトー:
- クミン
- コリアンダー
- パプリカ
プルコギ:
- 唐辛子
- ガーリック
ビビンバ:
- 唐辛子
- ガーリック
チヂミ:
- 唐辛子
- ガーリック
フォー:
- 唐辛子
- コリアンダー
- バジル
おにぎり:
- 生姜
トースト:
- シナモン
納豆ご飯:
- からし
卵かけご飯:
- ブラックペッパー
- 生姜
フルーツヨーグルト:
- シナモン
- ホワイトペッパー
シリアル:
- シナモン
オートミール:
- シナモン
おかゆ:
- 生姜
みそ汁:
- 生姜
スムージー:
- シナモン
フルーツサラダ:
- パセリ
ざるそば:
- わさび
- 生姜
- 唐辛子
うどん:
- 唐辛子
そうめん:
- わさび
- 生姜
ひやむぎ:
- 唐辛子
冷やし中華:
- からし
お茶漬け:
- 生姜
- わさび
サラダ:
- パセリ
シーザーサラダ:
- パセリ
コブサラダ:
- パセリ
- ブラックペッパー
- クミン
豆腐サラダ:
- パセリ
海藻サラダ:
- パセリ
ポテトサラダ:
- パセリ
- ブラックペッパー
冷奴:
- 生姜
湯豆腐:
- 生姜
- 唐辛子
野菜炒め:
- ガーリック
水ナスの浅漬け:
- 生姜
- わさび
浅漬け:
- 生姜
酢の物:
- 生姜
コンソメスープ:
- ローレル
- ブラックペッパー
- パセリ
ミネストローネ:
- ローレル
- バジル
- パセリ
コーンスープ:
- ホワイトペッパー
わかめスープ:
- 生姜
春雨スープ:
- 生姜
- ブラックペッパー
卵スープ:
- ブラックペッパー
クラムチャウダー:
- ホワイトペッパー
茶碗蒸し:
- 生姜
カプレーゼ:
- パセリ
- ホワイトペッパー
サンドイッチ:
- マスタード
かき氷:
- シナモン
スパイスコーラ:
- シナモン
- クローブ
- カルダモン
アイスクリーム:
- シナモン
- ブラックペッパー
フルーツサンド:
- パセリ
プリン:
- シナモン
ゼリー:
- シナモン
チャイ:
- シナモン
- カルダモン
スパイスクッキー:
- シナモン
- ナツメグ
ホットドッグ:
- マスタード
シュウマイ:
- からし
カルパッチョ:
- ブラックペッパー
- ローレル
